workspace(name = "binaries")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("@//:versions.bzl", "MINIKUBE_VERSION")

http_archive(
    name = "rules_pkg",
    url = "https://github.com/bazelbuild/rules_pkg/releases/download/0.3.0/rules_pkg-0.3.0.tar.gz",
    sha256 = "6b5969a7acd7b60c02f816773b06fcf32fbe8ba0c7919ccdc2df4f8fb923804a",
)
load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")

rules_pkg_dependencies()

http_archive(
    name = "minikube-linux-amd64",
    urls = ["https://github.com/kubernetes/minikube/releases/download/v%s/minikube-linux-amd64.tar.gz" % MINIKUBE_VERSION],
    sha256 = "8346947625cd6607eb7d0be4fe0c8b76ee9f9bce6ab1dbb433dcd2006067bb8e",
    build_file = "@//:minikube/minikube-linux-amd64.BUILD",
)
